/**
 * JWT Payload structure matching the backend's token generation.
 * Generated by Spring Boot's buildToken() method with roles claim added.
 *
 * Standard JWT claims:
 * - sub: Subject (user identifier) - from UserDetails.getUsername()
 * - iat: Issued At (Unix timestamp in seconds)
 * - exp: Expiration (Unix timestamp in seconds)
 * - jti: JWT ID (unique token identifier - UUID string)
 *
 * Custom claims:
 * - roles: Array of user roles from SecurityUser.getAuthorities()
 *
 * @see AuthServiceImpl.buildToken() - Backend token generation
 * @see AuthServiceImpl.generateUserClaims() - Custom roles claim
 */
export interface JwtPayload {
  /** JWT standard claim: Subject (user identifier) */
  sub?: string;

  /** JWT standard claim: Issued At (Unix timestamp in seconds) */
  iat?: number;

  /** JWT standard claim: Expiration (Unix timestamp in seconds) */
  exp?: number;

  /** JWT standard claim: JWT ID (unique token identifier) */
  jti?: string;

  /** Custom claim: User roles (e.g., ["ADMIN", "MEMBER", "TRAINER"]) */
  roles?: string[];

  /** Allow additional unknown claims for future extensibility */
  [key: string]: unknown;
}

/**
 * Type guard to validate if a value is a valid JwtPayload.
 * Ensures the payload has the required shape before use.
 */
export function isValidJwtPayload(value: unknown): value is JwtPayload {
  if (!value || typeof value !== "object") {
    return false;
  }

  const obj = value as Record<string, unknown>;

  // At minimum, expect common JWT claims or roles
  return (
    typeof obj.sub === "string" ||
    typeof obj.jti === "string" ||
    Array.isArray(obj.roles)
  );
}

/**
 * Safely extracts user roles from a JWT payload.
 * Returns empty array if roles are not present or invalid.
 */
export function extractRolesFromPayload(payload: unknown): string[] {
  if (!isValidJwtPayload(payload) || !Array.isArray(payload.roles)) {
    return [];
  }

  return payload.roles;
}

/**
 * Check if a JWT token is expired based on the exp claim.
 */
export function isTokenExpired(payload: JwtPayload): boolean {
  if (!payload.exp) {
    return true;
  }

  // exp is in seconds, Date.now() is in milliseconds
  return payload.exp * 1000 < Date.now();
}

